name: relocatewithusjobs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installing necessary packages
        run: pip install requests beautifulsoup4 pandas

      - name: Run the scraping script
        run: python relocatewithus.py || echo "Script failed, continuing workflow"

      - name: Parse alljobs.json into table
        id: parse-json
        run: |
          echo "# Latest Jobs" > README.md
          echo "" >> README.md
          echo "This page is updated at $(TZ='Asia/Kolkata' date +'%B %d, %Y %H:%M:%S')" >> README.md
          echo "" >> README.md
          echo "| Job Location | Visa Sponsorship | Company Name | Job Link | Job Posted On | Date Posted |" >> README.md
          echo "| --- | --- | --- | --- | --- | --- |" >> README.md
          while IFS="|" read -r job_location visa_sponsorship company_name job_link job_posted_on date_posted; do
            if [[ ! -z "$job_location" && ! -z "$visa_sponsorship" && ! -z "$company_name" && ! -z "$job_link" && ! -z "$job_posted_on" && ! -z "$date_posted" ]]; then
              echo "| $job_location | $visa_sponsorship | $company_name | [Apply]($job_link) | $job_posted_on | $date_posted |" >> README.md
            fi
          done < <(jq -r '.[] | "\(.Job_location)|\(.Visa_sponsorship_available)|\(.company_name)|\(.job_link)|\(.Job_posted_on)|\(.DatePosted)"' alljobs.json) || echo "JSON parsing failed"

      - name: Set Git user credentials
        run: |
          git config --global user.name "Suresh Parimi"
          git config --global user.email "reachparimi@gmail.com"

      - name: Pull changes from the remote repository
        run: git pull

      - name: Commit and push if it changed
        run: |
          git add README.md
          timestamp=$(date -u)
          git commit -m "Latest jobs: ${timestamp}" || exit 0
          git push
